# Analyse et Prédiction du Prix des Voitures d'Occasion

## Introduction
Ce projet s'inscrit dans une démarche d'expertise en données appliquée au marché automobile. L'objectif est d'utiliser un jeu de données provenant de la plateforme CarDekho pour comprendre quels facteurs influencent le prix de vente d'un véhicule. Grâce à l'apprentissage automatique, nous allons construire un modèle capable d'estimer la valeur d'une voiture de manière objective.

## Objectifs du Projet
* Exploration des données : Analyser les informations disponibles, comme l'année de fabrication, le kilométrage et le type de carburant, pour en extraire des statistiques clés.
* Visualisation : Utiliser des graphiques pour identifier les tendances et les relations entre les caractéristiques techniques et le prix.
* Modélisation : Appliquer la régression linéaire pour quantifier l'impact de l'âge et du kilométrage sur le prix de vente.
* Aide à la décision : Fournir une estimation précise pour un profil d'acheteur spécifique, comme dans le cas de la requête de Martin.

## Méthodologie
Le travail est divisé en plusieurs étapes :
1. Chargement et nettoyage des données avec la bibliothèque Pandas.
2. Analyse statistique et visualisation avec Matplotlib et Seaborn.
3. Mise en œuvre de modèles de régression avec Scikit-Learn et Scipy.
4. Évaluation de la précision des prédictions.

In [10]:
import pandas as pd 
import numpy as np

import matplotlib.pyplot as plt 
import seaborn as sns

In [11]:
# Création du data frame pandas à partir du fichier .csv fourni.
df_cars = pd.read_csv(r'C:\Users\Paul-Emmanuel Buffe\Desktop\la_plateforme\travaux_la_plateforme\new-car\data\carData.csv')

In [12]:
df_cars.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [17]:
df_cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB

In [13]:
df_cars.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [15]:
# Recherche des valeurs uniques

colonnes = ['Fuel_Type','Seller_Type', 'Transmission', 'Owner']

for col in colonnes:
    print(f"Valeurs uniques pour {col}: {df_cars[col].unique()}")

Valeurs uniques pour Fuel_Type: ['Petrol' 'Diesel' 'CNG']
Valeurs uniques pour Seller_Type: ['Dealer' 'Individual']
Valeurs uniques pour Transmission: ['Manual' 'Automatic']
Valeurs uniques pour Owner: [0 1 3]

In [20]:
# Recherche des doublons éventuels
nb_doublons = df_cars.duplicated().sum()

print(f"Nombre de lignes en doublon : {nb_doublons}")

Nombre de lignes en doublon : 2

In [28]:
print(df_cars[df_cars.duplicated(keep=False)])

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
15    ertiga  2016           7.75          10.79       43000    Diesel
17    ertiga  2016           7.75          10.79       43000    Diesel
51  fortuner  2015          23.00          30.61       40000    Diesel
93  fortuner  2015          23.00          30.61       40000    Diesel

   Seller_Type Transmission  Owner
15      Dealer       Manual      0
17      Dealer       Manual      0
51      Dealer    Automatic      0
93      Dealer    Automatic      0